// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	SmsCodeInput
	SmsCodeOutput
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SmsCodeInput struct {
	Phone string `protobuf:"bytes,2,opt,name=Phone" json:"Phone,omitempty"`
}

func (m *SmsCodeInput) Reset()                    { *m = SmsCodeInput{} }
func (m *SmsCodeInput) String() string            { return proto.CompactTextString(m) }
func (*SmsCodeInput) ProtoMessage()               {}
func (*SmsCodeInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SmsCodeInput) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type SmsCodeOutput struct {
	VerificationCode string `protobuf:"bytes,2,opt,name=VerificationCode" json:"VerificationCode,omitempty"`
}

func (m *SmsCodeOutput) Reset()                    { *m = SmsCodeOutput{} }
func (m *SmsCodeOutput) String() string            { return proto.CompactTextString(m) }
func (*SmsCodeOutput) ProtoMessage()               {}
func (*SmsCodeOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SmsCodeOutput) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func init() {
	proto.RegisterType((*SmsCodeInput)(nil), "user.SmsCodeInput")
	proto.RegisterType((*SmsCodeOutput)(nil), "user.SmsCodeOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	SmsCode(ctx context.Context, in *SmsCodeInput, opts ...grpc.CallOption) (*SmsCodeOutput, error)
	StreamSmsCode(ctx context.Context, in *SmsCodeInput, opts ...grpc.CallOption) (User_StreamSmsCodeClient, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) SmsCode(ctx context.Context, in *SmsCodeInput, opts ...grpc.CallOption) (*SmsCodeOutput, error) {
	out := new(SmsCodeOutput)
	err := grpc.Invoke(ctx, "/user.User/SmsCode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) StreamSmsCode(ctx context.Context, in *SmsCodeInput, opts ...grpc.CallOption) (User_StreamSmsCodeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_User_serviceDesc.Streams[0], c.cc, "/user.User/StreamSmsCode", opts...)
	if err != nil {
		return nil, err
	}
	x := &userStreamSmsCodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type User_StreamSmsCodeClient interface {
	Recv() (*SmsCodeOutput, error)
	grpc.ClientStream
}

type userStreamSmsCodeClient struct {
	grpc.ClientStream
}

func (x *userStreamSmsCodeClient) Recv() (*SmsCodeOutput, error) {
	m := new(SmsCodeOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for User service

type UserServer interface {
	SmsCode(context.Context, *SmsCodeInput) (*SmsCodeOutput, error)
	StreamSmsCode(*SmsCodeInput, User_StreamSmsCodeServer) error
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_SmsCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsCodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SmsCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/SmsCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SmsCode(ctx, req.(*SmsCodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_StreamSmsCode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SmsCodeInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServer).StreamSmsCode(m, &userStreamSmsCodeServer{stream})
}

type User_StreamSmsCodeServer interface {
	Send(*SmsCodeOutput) error
	grpc.ServerStream
}

type userStreamSmsCodeServer struct {
	grpc.ServerStream
}

func (x *userStreamSmsCodeServer) Send(m *SmsCodeOutput) error {
	return x.ServerStream.SendMsg(m)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SmsCode",
			Handler:    _User_SmsCode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSmsCode",
			Handler:       _User_StreamSmsCode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x54, 0xb8, 0x78, 0x82, 0x73,
	0x8b, 0x9d, 0xf3, 0x53, 0x52, 0x3d, 0xf3, 0x0a, 0x4a, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x03, 0x32,
	0xf2, 0xf3, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x25, 0x6b, 0x2e, 0x5e,
	0xa8, 0x2a, 0xff, 0xd2, 0x12, 0x90, 0x32, 0x2d, 0x2e, 0x81, 0xb0, 0xd4, 0xa2, 0xcc, 0xb4, 0xcc,
	0xe4, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x90, 0x0c, 0x54, 0x07, 0x86, 0xb8, 0x51, 0x15, 0x17, 0x4b,
	0x68, 0x71, 0x6a, 0x91, 0x90, 0x09, 0x17, 0x3b, 0xd4, 0x10, 0x21, 0x21, 0x3d, 0xb0, 0x43, 0x90,
	0x6d, 0x96, 0x12, 0x46, 0x11, 0x83, 0xd8, 0xa3, 0xc4, 0x20, 0x64, 0xc3, 0xc5, 0x1b, 0x5c, 0x52,
	0x94, 0x9a, 0x98, 0x4b, 0xba, 0x5e, 0x03, 0xc6, 0x24, 0x36, 0xb0, 0x5f, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xb9, 0xb3, 0x99, 0xde, 0xf9, 0x00, 0x00, 0x00,
}
